In [649]:
from sklearn.decomposition import TruncatedSVD
from scipy.sparse.linalg import svds

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import csv 
import os

In [667]:
# user id 생성

# 57 *(userid의 갯수) 개 만큼의 행이 존재
user=pd.DataFrame(columns=['userid',"areaid","rating"])

def create_user(n):
    idx=0
    coin=0
    for nn in range(n):
        a=[]
        for i in range(57):
            # if (coin+i%3==0):
            a.append(nn+1) # userid
            a.append(i) # areaid
            a.append(np.random.randint(0, 6)) # random rating
            user.loc[idx]=a
            a=[]
            idx+=1
            coin+=1
create_user(30)


In [668]:
user.shape

(1710, 3)

In [676]:
user
# 일부 행 삭제
for i in range(len(user)-2):
    if i%100==0:
        user.drop(user.index[i],inplace=True)
print(len(user))
for i in range(len(user)-2):
    if i%100==0:
        user.drop(user.index[i],inplace=True)
print(len(user))
for i in range(len(user)-2):
    if i%100==0:
        user.drop(user.index[i],inplace=True)
print(len(user))
for i in range(len(user)-2):
    if i%200==0:
        user.drop(user.index[i],inplace=True)
print(len(user))
for i in range(len(user)-2):
    if i%150==0:
        user.drop(user.index[i],inplace=True)
print(len(user))

1468
1453
1438
1430
1420


In [677]:
# areaid 생성
df=pd.read_csv('../data/info_data.csv',encoding='utf-8',sep='|')
# 57 개 만큼의 행이 존재

area=pd.DataFrame(columns=['areaid',"title","genres"])

a=[]
idx=0
for i in range(57):
    a.append(i) # movieid
    a.append(df.iloc[idx,0]) # title
    a.append(df.iloc[idx,33]) # genres
    area.loc[idx]=a
    a=[]
    idx+=1


In [678]:
area

areaid                title   genres
0       0           서울공연예술연습공간    서울특별시
1       1             아르코예술기록원    서울특별시
2       2           청주공연예술연습공간     충청북도
3       3           아르코예술인력개발원      경기도
4       4           전주공연예술연습공간     전라북도
5       5           춘천공연예술연습공간      강원도
6       6           세종공연예술연습공간  세종특별자치시
7       7           창원공연예술연습공간     경상남도
8       8           강진공연예술연습공간     전라남도
9       9           금정공연예술연습공간    부산광역시
10     10           서천공연예술연습공간     충청남도
11     11           부산공연예술연습공간    부산광역시
12     12           광주공연예술연습공간    광주광역시
13     13           부천공연예술연습공간      경기도
14     14           인천공연예술연습공간    인천광역시
15     15           울산공연예술연습공간    울산광역시
16     16                예술가의집    서울특별시
17     17           대구공연예술연습공간    대구광역시
18     18           포항공연예술연습공간     경상북도
19     19           원주공연예술연습공간      강원도
20     20                 예울마루     전라남도
21     21               고흥문화회관     전라남도
22     22              영광예술의전당     전라남도
23     23              남도소리울림터     전라남도
24     24               강진군아트홀     전라남도
25     25             곡성레저문화센터     전라남도
26     26             광양문화예술회관     전라남도
27     27             구례문화예술회관     전라남도
28     28             나주문화예술회관     전라남도
29     29               담양문화회관     전라남도
30     30             장성문화예술회관     전라남도
31     31            목포시문화예술회관     전라남도
32     32           무안승달문화예술회관     전라남도
33     33            보성군문화예술회관     전라남도
34     34             순천문화예술회관     전라남도
35     35               여수시민회관     전라남도
36     36            완도문화예술의전당     전라남도
37     37             장흥문화예술회관     전라남도
38     38             진도향토문화회관     전라남도
39     39             해남문화예술회관     전라남도
40     40        밀양 누루(樓樓) 미술관     경상남도
41     41                우리미술관    인천광역시
42     42           소금나루 작은미술관    울산광역시
43     43            바래길 작은미술관     경상남도
44     44      장생포고래로131 작은미술관    울산광역시
45     45            작은미술관 보구곶      경기도
46     46             서동 작은미술관    부산광역시
47     47          아트터미널 작은미술관      강원도
48     48             악양 작은미술관     경상남도
49     49       노인과 둔장바다 작은미술관     전라남도
50     50  기억을 모으는 미술관 ART-TEA      강원도
51     51            BRT 작은미술관  세종특별자치시
52     52  정라항 그리go 작은미술관 4048      강원도
53     53  정라항 그리go 작은미술관 5223      강원도
54     54  정라항 그리go 작은미술관 5219      강원도
55     55  정라항 그리go 작은미술관 1116      강원도
56     56            봉평콧등작은미술관      강원도

In [679]:
# 저장
user.to_csv('../data/df_user.csv',index=False)
area.to_csv('../data/df_area.csv',index=False)


In [680]:
df_area=pd.read_csv('../data/df_area.csv',encoding='utf-8')
df_user=pd.read_csv('../data/df_user.csv',encoding='utf-8')

In [681]:
# 전처리
# df_area.drop('genres',axis=1,inplace=True)
# df_area.head()

In [682]:
user_area_data=pd.merge(df_user,df_area,on="areaid")
user_area_data

userid  areaid  rating       title genres
0          1      16       3       예술가의집  서울특별시
1          2      16       1       예술가의집  서울특별시
2          4      16       1       예술가의집  서울특별시
3          6      16       5       예술가의집  서울특별시
4          7      16       2       예술가의집  서울특별시
...      ...     ...     ...         ...    ...
1415      25       4       0  전주공연예술연습공간   전라북도
1416      27       4       3  전주공연예술연습공간   전라북도
1417      28       4       1  전주공연예술연습공간   전라북도
1418      29       4       2  전주공연예술연습공간   전라북도
1419      30       4       5  전주공연예술연습공간   전라북도

[1420 rows x 5 columns]

In [683]:
print(df_user.tail(20))

      userid  areaid  rating
1400      30      35       3
1401      30      36       5
1402      30      37       5
1403      30      38       2
1404      30      39       5
1405      30      40       3
1406      30      41       0
1407      30      43       3
1408      30      44       4
1409      30      45       1
1410      30      46       4
1411      30      47       2
1412      30      49       4
1413      30      50       3
1414      30      51       3
1415      30      52       5
1416      30      53       0
1417      30      54       3
1418      30      55       4
1419      30      56       4


In [684]:
user_area_data.shape

(1420, 5)

In [685]:
user_area_rating = user_area_data.pivot_table(index = 'userid', columns='areaid',values='rating',aggfunc='first').fillna(0)

In [686]:
user_area_rating.shape

(30, 57)

In [687]:
user_area_rating.head()

areaid   0    1    2    3    4    5    6    7    8    9   ...   47   48   49  \
userid                                                    ...                  
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  4.0  0.0  4.0   
2       3.0  0.0  2.0  2.0  0.0  0.0  0.0  5.0  2.0  0.0  ...  0.0  5.0  0.0   
3       0.0  1.0  0.0  4.0  0.0  4.0  0.0  0.0  3.0  2.0  ...  2.0  5.0  3.0   
4       3.0  3.0  0.0  0.0  0.0  0.0  0.0  4.0  3.0  0.0  ...  1.0  0.0  4.0   
5       0.0  0.0  5.0  1.0  1.0  0.0  4.0  2.0  0.0  4.0  ...  2.0  3.0  1.0   

areaid   50   51   52   53   54   55   56  
userid                                     
1       4.0  0.0  3.0  0.0  1.0  0.0  0.0  
2       4.0  0.0  0.0  0.0  0.0  0.0  2.0  
3       2.0  0.0  1.0  5.0  3.0  5.0  0.0  
4       4.0  0.0  4.0  5.0  0.0  1.0  5.0  
5       0.0  5.0  1.0  4.0  3.0  2.0  4.0  

[5 rows x 57 columns]

In [688]:
# matrix는 pivot_table 값을 numpy matrix로 만든 것 
matrix = user_area_rating.values
# user_ratings_mean은 사용자의 평균 평점 
user_ratings_mean = np.mean(matrix, axis = 1)

# R_user_mean : 사용자-영화에 대해 사용자 평균 평점을 뺀 것.
matrix_user_mean = matrix - user_ratings_mean.reshape(-1, 1)

In [689]:
matrix

array([[0., 0., 0., ..., 1., 0., 0.],
       [3., 0., 2., ..., 0., 0., 2.],
       [0., 1., 0., ..., 3., 5., 0.],
       ...,
       [3., 1., 4., ..., 1., 3., 0.],
       [0., 4., 4., ..., 2., 3., 1.],
       [5., 0., 4., ..., 3., 4., 4.]])

In [690]:
matrix.shape

(30, 57)

In [691]:
user_ratings_mean.shape

(30,)

In [692]:
matrix_user_mean.shape

(30, 57)

In [693]:
pd.DataFrame(matrix_user_mean, columns = user_area_rating.columns).head()

areaid        0         1         2         3         4         5         6   \
0      -1.421053 -1.421053 -1.421053 -1.421053 -1.421053 -1.421053 -1.421053   
1       0.596491 -2.403509 -0.403509 -0.403509 -2.403509 -2.403509 -2.403509   
2      -2.263158 -1.263158 -2.263158  1.736842 -2.263158  1.736842 -2.263158   
3       0.964912  0.964912 -2.035088 -2.035088 -2.035088 -2.035088 -2.035088   
4      -1.964912 -1.964912  3.035088 -0.964912 -0.964912 -1.964912  2.035088   

areaid        7         8         9   ...        47        48        49  \
0      -1.421053 -1.421053 -1.421053  ...  2.578947 -1.421053  2.578947   
1       2.596491 -0.403509 -2.403509  ... -2.403509  2.596491 -2.403509   
2      -2.263158  0.736842 -0.263158  ... -0.263158  2.736842  0.736842   
3       1.964912  0.964912 -2.035088  ... -1.035088 -2.035088  1.964912   
4       0.035088 -1.964912  2.035088  ...  0.035088  1.035088 -0.964912   

areaid        50        51        52        53        54        55        56  
0       2.578947 -1.421053  1.578947 -1.421053 -0.421053 -1.421053 -1.421053  
1       1.596491 -2.403509 -2.403509 -2.403509 -2.403509 -2.403509 -0.403509  
2      -0.263158 -2.263158 -1.263158  2.736842  0.736842  2.736842 -2.263158  
3       1.964912 -2.035088  1.964912  2.964912 -2.035088 -1.035088  2.964912  
4      -1.964912  3.035088 -0.964912  2.035088  1.035088  0.035088  2.035088  

[5 rows x 57 columns]

In [694]:

# scipy에서 제공해주는 svd.  
# U 행렬, sigma 행렬, V 전치 행렬을 반환.

U, sigma, Vt = svds(matrix_user_mean, k = 12)

In [695]:
print(U.shape)
print(sigma.shape)
print(Vt.shape)

(30, 12)
(12,)
(12, 57)


In [696]:
sigma = np.diag(sigma)

In [697]:
sigma.shape

(12, 12)

In [698]:
sigma[0]

array([14.23911137,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ])

In [699]:
sigma[1]

array([ 0.       , 14.5603443,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
        0.       ,  0.       ])

In [700]:
# U, Sigma, Vt의 내적을 수행하면, 다시 원본 행렬로 복원이 된다. 
# 거기에 + 사용자 평균 rating을 적용한다. 
svd_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)

In [701]:
df_svd_preds = pd.DataFrame(svd_user_predicted_ratings, columns = user_area_rating.columns)
df_svd_preds.head()

areaid        0         1         2         3         4         5         6   \
0       0.874532  0.338547 -0.273507  1.125004  1.437953  0.310381  0.882117   
1       3.629651  1.286686  1.368176  3.083774  0.118090  0.042830 -0.925084   
2       0.450070  1.856522 -0.087031  3.687422 -0.103011  2.390423  1.719677   
3       2.076011  2.482469  0.626469 -0.608392  0.699117  0.425802  0.249982   
4      -0.004907  0.455974  4.627291  1.544367  0.329680 -0.412844  3.854152   

areaid        7         8         9   ...        47        48        49  \
0       1.952133  0.087468 -0.072775  ...  3.023657  0.942883  3.480378   
1       5.255927  3.294667  0.574276  ... -0.060359  4.967275  0.648080   
2       0.593040  2.810138  3.073510  ...  1.135655  3.710894  3.017745   
3       2.570768  3.187467 -0.576284  ...  1.834042  0.220465  4.797034   
4       2.322405 -0.372725  4.264074  ...  1.912899  2.958295  0.627411   

areaid        50        51        52        53        54        55        56  
0       3.672999  0.335677  1.707069  0.003252  0.923776  0.997074  0.396717  
1       2.897183  0.926580  0.312816  1.249607 -0.647600  1.348352  1.688990  
2       2.444932 -0.751025  0.656225  5.242340  1.934065  3.609726 -0.144324  
3       4.138439  0.617185  4.198144  5.225274 -0.294843  1.605699  4.289851  
4      -0.834327  4.063018  1.482391  3.989427  3.105634  2.884416  1.786116  

[5 rows x 57 columns]

In [702]:
df_svd_preds.shape

(30, 57)

In [713]:
def recommend_areas(df_svd_preds, user_id, ori_df_area, ori_ratings_df, num_recommendations=5):
    
    #현재는 index로 적용이 되어있으므로 user_id - 1을 해야함.
    user_row_number = user_id - 1 

    # 최종적으로 만든 pred_df에서 사용자 index에 따라 영화 데이터 정렬 -> 영화 평점이 높은 순으로 정렬 됌
    sorted_user_predictions = df_svd_preds.iloc[user_row_number].sort_values(ascending=False)

    # 원본 평점 데이터에서 user id에 해당하는 데이터를 뽑아낸다. 
    user_data = ori_ratings_df[ori_ratings_df.userid == user_id]

    # 위에서 뽑은 user_data와 원본 영화 데이터를 합친다. 
    user_history = user_data.merge(df_area, on = 'areaid').sort_values(['rating'], ascending=False)

    # 원본 영화 데이터에서 사용자가 본 영화 데이터를 제외한 데이터를 추출
    recommendations = ori_df_area[~ori_df_area['areaid'].isin(user_history['areaid'])]

    # 모두 가봤다면 Empty로 에러가발생..
    # # 안본게 없다면 즉,
    if(recommendations.empty==True):# 공백이라면
        recommendations=ori_df_area # 다시 전부 추천

    # 사용자의 영화 평점이 높은 순으로 정렬된 데이터와 위 recommendations을 합친다. 

    recommendations = recommendations.merge( pd.DataFrame(sorted_user_predictions).reset_index(), on = 'areaid')

    # 컬럼 이름 바꾸고 정렬해서 return
    recommendations = recommendations.rename(columns = {user_row_number: 'Predictions'}).sort_values('Predictions', ascending = False).iloc[:num_recommendations, :]

    return user_history, recommendations

In [715]:
already_rated, predictions = recommend_areas(df_svd_preds, 29, df_area, df_user, 5)

In [716]:
already_rated.head(10)

userid  areaid  rating       title genres
23      29      25       5    곡성레저문화센터   전라남도
39      29      46       5    서동 작은미술관  부산광역시
33      29      39       5    해남문화예술회관   전라남도
30      29      35       5      여수시민회관   전라남도
38      29      45       5   작은미술관 보구곶    경기도
20      29      22       5     영광예술의전당   전라남도
27      29      30       5    장성문화예술회관   전라남도
2       29       2       4  청주공연예술연습공간   충청북도
16      29      17       4  대구공연예술연습공간  대구광역시
5       29       5       4  춘천공연예술연습공간    강원도

In [717]:
predictions

areaid                title genres  Predictions
7      48             악양 작은미술관   경상남도     2.062393
3      31            목포시문화예술회관   전라남도     1.853583
2      27             구례문화예술회관   전라남도     1.201624
4      34             순천문화예술회관   전라남도     1.093958
8      52  정라항 그리go 작은미술관 4048    강원도     0.949001

pandas.core.frame.DataFrame

In [ ]:
# 오케이
# 데이터에 대해서 
# ㅇㅇㅇㅇㅇ
# ㅇㅇㅇㅇ
# ㅇㅇㅇ
# ㅇㅇ
